# 项目在 SonarQube 中的唯一标识（必须和刚才在网页上创建的一致）
sonar.projectKey=sonar-test

# 项目显示名称（随便起，会显示在 SonarQube 界面上）
sonar.projectName=测试项目

# 项目版本（可选，但建议写上）
sonar.projectVersion=1.0

# 源代码所在的目录，相对于这个配置文件的路径
sonar.sources=src

# 源文件的编码
sonar.sourceEncoding=UTF-8

# SonarQube 服务端地址
sonar.host.url=http://localhost:9000

# 你刚才生成的 Token
sonar.token=sqa_265f8364654faec3d0d21f349109c74417c3dd6f